sonar.projectKey=ErickGarcia1920_NodeGoat
sonar.organization=erickgarcia1920
sonar.projectName=NodeGoat
sonar.sources=app,server.js
sonar.exclusions=node_modules/**,**/public/**,test/**
sonar.sourceEncoding=UTF-8
