sonar.projectKey=ErickGarcia1920_NodeGoat
sonar.organization=fe04ab673f7a791c5bcd575c26483254e61be6ec
sonar.projectName=NodeGoat
sonar.sources=app,server.js
sonar.exclusions=node_modules/**,**/public/**,test/**
sonar.sourceEncoding=UTF-8
